name: bitcount
version: 0.4.0
description: >-
  Provides efficient one-bits count method extension for default int.
homepage: https://github.com/akhomchenko/bitcount
repository: https://github.com/akhomchenko/bitcount

environment:
  sdk: ^3.7.0

dev_dependencies:
  test: ^1.31.0
  lints: ^5.1.1
  benchmark_harness: ^2.3.1
  frontend_server_client: ^4.0.0
