name: Test and Analyze

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * MON'

permissions:
  contents: read

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 3.7.0 # min
          - stable # max

    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test -p vm,node

      - name: Run example
        run: dart run example/example.dart

      - name: Downgrade dependencies
        run: dart pub downgrade

      - name: Analyze downgraded dependency resolution
        run: dart analyze

      - name: Run downgraded tests
        run: dart test -p vm,node
